'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Content.Solicitation.Primitives.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sample_snippet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sample_snippet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property screenshot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("screenshot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property screenshot_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("screenshot_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Snippet_Sample() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Snippet_Sample", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1
        '''#1
        '''2
        '''100%
        '''3
        '''100% free
        '''4
        '''100% satisfied
        '''5
        '''50% off
        '''6
        '''Ad
        '''7
        '''All New
        '''8
        '''Bargain
        '''9
        '''Best Price
        '''10
        '''Bonus
        '''11
        '''Brand New Pager
        '''12
        '''Claims not to be selling anything
        '''13
        '''Cost
        '''14
        '''Costs
        '''15
        '''Credit
        '''16
        '''Discount
        '''17
        '''Don’t delete
        '''18
        '''Email harvest
        '''19
        '''Email marketing
        '''20
        '''F r e e
        '''21
        '''Fast cash
        '''22
        '''For free
        '''23
        '''For instant access
        '''24
        '''For just $xxx
        '''25
        '''For just $yyy
        '''26
        '''For only
        '''27
        '''For you
        '''28
        '''Free
        '''29
        '''Free and free
        '''30
        '''Free consultation
        '''31
        '''Free dvd
        '''32
        '''Free gift
        '''33
        '''Free sample
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Span_Words() As String
            Get
                Return ResourceManager.GetString("Span_Words", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1
        '''#1
        '''2
        '''100%
        '''3
        '''100% free
        '''4
        '''100% satisfied
        '''5
        '''50% off
        '''6
        '''Ad
        '''7
        '''All New
        '''8
        '''Bargain
        '''9
        '''Best Price
        '''10
        '''Bonus
        '''11
        '''Brand New Pager
        '''12
        '''Claims not to be selling anything
        '''13
        '''Cost
        '''14
        '''Costs
        '''15
        '''Credit
        '''16
        '''Discount
        '''17
        '''Don’t delete
        '''18
        '''Email harvest
        '''19
        '''Email marketing
        '''20
        '''F r e e
        '''21
        '''Fast cash
        '''22
        '''For free
        '''23
        '''For instant access
        '''24
        '''For just $xxx
        '''25
        '''For just $yyy
        '''26
        '''For only
        '''27
        '''For you
        '''28
        '''Free
        '''29
        '''Free and free
        '''30
        '''Free consultation
        '''31
        '''Free dvd
        '''32
        '''Free gift
        '''33
        '''Free sample
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Span_Words1() As String
            Get
                Return ResourceManager.GetString("Span_Words1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hello Allen,
        '''
        '''In these unpresidented times, we are hoping that you and
        '''your colleagues at the Northwind Trading Co are taking every 
        '''precaution to stay safe.
        '''
        '''We, at Expert 23, have swung our focus to the next
        '''challenge our Nation faces: the restart of our economy.
        '''
        '''Our company is a wholesale provider of B2B HQL leads and other
        '''customer acquistion solutions (webinars, video channels, etc).
        '''
        '''Our client list consists of a wide universe of companies. 
        '''We continue to work at full pace finding custo [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Test0() As String
            Get
                Return ResourceManager.GetString("Test0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hello Allen,
        '''
        '''In these unpresidented times, we are hoping that you and
        '''your colleagues at the Northwind Trading Co are taking every 
        '''precaution to stay safe.
        '''
        '''We, at Expert 23, have swung our focus to the next
        '''challenge our Nation faces: the restart of our economy.
        '''
        '''Our company is a wholesale provider of B2B HQL leads and other
        '''customer acquistion solutions (webinars, video channels, etc).
        '''
        '''Our client list consists of a wide universe of companies. 
        '''We continue to work at full pace finding custo [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Test01() As String
            Get
                Return ResourceManager.GetString("Test01", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
